server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: vehicle-service
              uri: lb://vehicle-service
              predicates:
                - Path=/api/v1/vehicle/**
            - id: parking-service
              uri: lb://parking-service
              predicates:
                - Path=/api/v1/parking/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/