server:
  port: 8083

spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:mysql://localhost:3306/SmartParkingSystem?createDatabaseIfNotExist=true
    username: root
    password: Ijse@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

